spring:
  application:
    name: drivers-hub-services-dev
  datasource:
    url: jdbc:postgresql://${APPLICATION_DATABASE_HOST}:${APPLICATION_DATABASE_PORT}/${APPLICATION_DATABASE_NAME}?currentSchema=${APPLICATION_DATABASE_SCHEMA}
    username: ${APPLICATION_DATABASE_USER}
    password: ${APPLICATION_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: "file:.env[.properties]"
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus.metrics
  prometheus:
    metrics:
      export:
        enabled: true
logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.boot.context.config: DEBUG