spring:
  application:
    name: drivers-hub-services
  liquibase:
    enabled: false
    change-log: "classpath:db/changelog/db.changelog.sql"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus.metrics
  prometheus:
    metrics:
      export:
        enabled: true