spring:
  application:
    name: drivers-hub-services

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus.metrics
  prometheus:
    metrics:
      export:
        enabled: true